export default  {
  data: [
    {id: 1, name: 'React Cafe', address: '123 Anywhere St', image: "https://s3-media3.fl.yelpcdn.com/bphoto/--8oiPVp0AsjoWHqaY1rDQ/o.jpg", rating: 5},
    {id: 2, name: 'Fancy Restaurant', address: '799 Main St', image: 'https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg', rating: 3.5},
    {id: 3, name: 'Taco Place', address: '550 Maple Rd', image: 'https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg', rating: 4.5},
    {id: 4, name: "Tony's Diner", address: '4101 College St', image: 'https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg', rating: 4},
    {id: 5, name: 'Pasta Central', address: '706 Harper St', image: 'circle.png', rating: 3},
    {id: 6, name: 'Burger Builder', address: '4869 Hamilton Dr', image: "https://s3-media3.fl.yelpcdn.com/bphoto/--8oiPVp0AsjoWHqaY1rDQ/o.jpg", rating: 1.5},
    {id: 7, name: 'Pizza Express', address: '1049 Bird St', image: 'https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg', rating: 3.5},
    {id: 8, name: 'Teriyaki To Go', address: '1885 Tea Berry Lane', image: 'https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg', rating: 3},
    {id: 9, name: 'Maroon Deli', address: '1082 Stuart St', image: 'circle.png', rating: 4.5},
    {id: 10, name: 'Prime Bar and Grill', address: '1848 Fairfax Dr', image: "https://s3-media3.fl.yelpcdn.com/bphoto/--8oiPVp0AsjoWHqaY1rDQ/o.jpg", rating: 4.5},
    {id: 11, name: 'Dumpling House', address: '747 Kelly Dr', image: 'https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg', rating: 5},
    {id: 12, name: 'Hot Chicken', address: '1816 Olive St', image: 'https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg', rating: 3.5},
    {id: 13, name: "Luna's Tap Room", address: '3256 Spirit Dr', image: 'circle.png', rating: 3},
    {id: 14, name: 'Quick Sandwich Shop', address: '2587 Cherry Ridge Dr', image: "https://s3-media3.fl.yelpcdn.com/bphoto/--8oiPVp0AsjoWHqaY1rDQ/o.jpg", rating: 4.5},
    {id: 15, name: "Bobby's Burgers", address: '4152 Berkley St', image: 'https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg', rating: 5},
    {id: 16, name: 'Turnpike Diner', address: '4571 Central Ave', image: 'https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg', rating: 2.5},
    {id: 17, name: 'Bombay Express', address: '65 Queens Lane', image: 'circle.png', rating: 3.5},
    {id: 18, name: 'Coffee Central', address: '3228 Oakwood Circle', image: "https://s3-media3.fl.yelpcdn.com/bphoto/--8oiPVp0AsjoWHqaY1rDQ/o.jpg", rating: 4.5},
    {id: 19, name: "King's Garden", address: '2935 Victoria Ct', image: 'https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg', rating: 5},
    {id: 20, name: 'Salads and More', address: '2454 Preston St', image: 'https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg', rating: 2},
    {id: 21, name: 'Quick Sandwich Shop', address: '2587 Cherry Ridge Dr', image: "https://s3-media3.fl.yelpcdn.com/bphoto/--8oiPVp0AsjoWHqaY1rDQ/o.jpg", rating: 4.5},
    {id: 22, name: "Bobby's Burgers", address: '4152 Berkley St', image: 'https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg', rating: 5},
    {id: 23, name: 'Turnpike Diner', address: '4571 Central Ave', image: 'https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg', rating: 2.5},
    {id: 24, name: 'Bombay Express', address: '65 Queens Lane', image: 'circle.png', rating: 3.5},
    {id: 25, name: 'Coffee Central', address: '3228 Oakwood Circle', image: "https://s3-media3.fl.yelpcdn.com/bphoto/--8oiPVp0AsjoWHqaY1rDQ/o.jpg", rating: 4.5},
    {id: 26, name: "King's Garden", address: '2935 Victoria Ct', image: 'https://s3-media4.fl.yelpcdn.com/bphoto/HZVDyYaghwPl2kVbvHuHjA/o.jpg', rating: 5},
    {id: 27, name: 'Salads and More', address: '2454 Preston St', image: 'https://s3-media2.fl.yelpcdn.com/bphoto/CPc91bGzKBe95aM5edjhhQ/o.jpg', rating: 2},
  ]
}